### ISSUE TITLE
Error in sample app on https://www.gomponents.com/ home page

### ISSUE THREAD

**Issue by sgj100** [maragudk/gomponents.com#11]
The sample app contained on the https://www.gomponents.com/ home page contains an error. Trying to compile it produces the following error:

./main.go:84:19: type int of len(links) does not match []T (cannot infer T)

The relevant lines are currently

				g.Group(g.Map(len(links), func(i int) g.Node {
					return NavbarLink(links[i].Path, links[i].Name, currentPath == links[i].Path)
				})),

and should be something like

				g.Group(g.Map(links, func(p PageLink) g.Node {
					return NavbarLink(p.Path, p.Name, currentPath == p.Path)
				})),

**Comment by markuswustenberg** [comment]
@sgj100 thank you for bringing this to my attention, and sorry for the wait! I had forgotten to watch this repository… I'll get it fixed. 😊
