### ISSUE TITLE
new lib: Bulma-Gomponents

### ISSUE THREAD

**Issue by willoma** [maragudk/gomponents.com#20]
Hello,

I have just released [Bulma-Gomponents](https://willoma.github.io/bulma-gomponents/), a lib that uses Gomponents to make it easy to create interfaces with Bulma.

**Comment by markuswustenberg** [comment]
Hi @willoma. Super cool! :D I'm a bit behind on updating the web page, will have a look at this, hopefully next week.

**Comment by markuswustenberg** [comment]
@willoma sorry about the delay, we are absolutely plagued by colds in the family at the moment. 🤧

I've added Bulma to the site, thank you for that! If you like, could you provide an example that you think expresses your library's functionality best? See the other examples at https://www.gomponents.com/plus/ for what I mean.

**Comment by willoma** [comment]
Here is an example:

```go
package main

import (
	g "github.com/maragudk/gomponents"
	b "github.com/willoma/bulma-gomponents"
)

func Navbar() g.Node {
	return b.Navbar(
		b.Dark,
		b.NavbarStart(
			b.NavbarAHref("/", "Home"),
			b.NavbarAHref("/about", "About"),
		),
	)
}
```

**Comment by markuswustenberg** [comment]
Thank you! Should be live in a minute. 🙂
